CREATE TABLE `office`.`student` (
	`id` int(9) NOT NULL COMMENT '学号',
	`name` varchar(30) NOT NULL COMMENT '姓名',
	`sex` char(50) NOT NULL COMMENT '性别',
	`major` varchar(80) NOT NULL COMMENT '专业',
	`class` varchar(7) NOT NULL COMMENT '行政班',
	`poc` varchar(20) NOT NULL DEFAULT '' COMMENT '政治面貌',
	`ethnic` varchar(15) NOT NULL DEFAULT '' COMMENT '民族',
	`personid` varchar(18) NOT NULL COMMENT '身份证号',
	`from` varchar(20) NOT NULL COMMENT '生源地',
	`position` varchar(20) COMMENT '职务',
	`phone` int(11) NOT NULL COMMENT '本人联系方式',
	`parentsphone` int(11) COMMENT '家长联系方式',
	`fathername` varchar(30) COMMENT '父亲姓名',
	`mothername` varchar(30) COMMENT '母亲姓名',
	`isloan` int(1) NOT NULL DEFAULT 0 COMMENT '是否贷款',
	`isdifficult` int(1) NOT NULL DEFAULT 0 COMMENT '困难等级',
	`type` varchar(12) NOT NULL DEFAULT '' COMMENT '考试类别',
	`religious` varchar(15) NOT NULL DEFAULT '' COMMENT '宗教信仰',
	`isAlone` int(1) NOT NULL DEFAULT 0 COMMENT '是否单亲',
	`comment` varchar(160),
	PRIMARY KEY (`id`)
) COMMENT='';